apiVersion: v1
kind: PersistentVolumeClain
metadata:
  name: mysql-dados
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
    template:
      metadata:
        labels:
          app: mysql
      spec:
        containers:
        - image: klebermarcal/database:1.0
        args:
        -  "--ignore-db-dir=lost+found"
        imagePullPolicy: Always
        name: mysql
        ports:
        -containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-dados
          persistentMoclumeClain:
            claimName: mysql-dados

---

apiVersion: apps/v1
kind: Deployment
medatada:
  name: php
  labels:
    app: php
spec:
  replicas: 6
  selector:
    matchlabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spce:
      containers:
      - name: php
        image: klebermarcal/backend:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
